/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Course;
import Backend.CourseService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Lenovo
 */
public class AdminDashboard extends javax.swing.JFrame {
    private CourseService cs = new CourseService();
    private Course course;
/**
         * Creates new form AdminDashboard
         */
        public AdminDashboard()
        {
            CourseService cs;
            initComponents();
            loadCourses();
            this.setLocationRelativeTo(null);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            Table = new javax.swing.JTable();
            LogoutBtn = new javax.swing.JButton();
            ApproveBtn = new javax.swing.JButton();
            DeclineBtn = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel1.setText("     Admin DashBoard");

            Table.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null, null},
                            {null, null, null},
                            {null, null, null},
                            {null, null, null}
                    },
                    new String [] {
                            "Course ID", "Course Name", "Status"
                    }
            ));
            jScrollPane1.setViewportView(Table);

            LogoutBtn.setText("Logout");
            LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    LogoutBtnActionPerformed(evt);
                }
            });

            ApproveBtn.setText("Approve");
            ApproveBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ApproveBtnActionPerformed(evt);
                }
            });

            DeclineBtn.setText("Decline");
            DeclineBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    DeclineBtnActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(95, 95, 95)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(201, 201, 201)
                                                    .addComponent(ApproveBtn)
                                                    .addGap(68, 68, 68)
                                                    .addComponent(DeclineBtn))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(278, 278, 278)
                                                    .addComponent(LogoutBtn))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(241, 241, 241)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(104, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(DeclineBtn)
                                            .addComponent(ApproveBtn))
                                    .addGap(18, 18, 18)
                                    .addComponent(LogoutBtn)
                                    .addGap(29, 29, 29))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ApproveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveBtnActionPerformed
            // TODO add your handling code here:
            editCourseStatus("Approve");
        }//GEN-LAST:event_ApproveBtnActionPerformed

        private void DeclineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineBtnActionPerformed
            // TODO add your handling code here:
            editCourseStatus("Decline");
        }//GEN-LAST:event_DeclineBtnActionPerformed

        private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
            // TODO add your handling code here:
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
           // this.dispose();
        }//GEN-LAST:event_LogoutBtnActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                   // new AdminDashboard().setVisible(true);
                }
            });
        }

    private void loadCourses(){
        ArrayList<Course> courses = cs.getAllCourses();

        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);

        for (Course c: courses){
            model.addRow(new Object[]{c.getCourseId(),c.getCourseName(),c.getStatus()});
        }

    }
    private void editCourseStatus(String status){
        int selectedRow = Table.getSelectedRow();
        if (selectedRow==-1){
            JOptionPane.showMessageDialog(this, "Please select a row first");
            return;
        }

        String courseId = Table.getValueAt(selectedRow,0).toString();

        if (status.equalsIgnoreCase("approve")) {
            cs.approveCourse(courseId);
            JOptionPane.showMessageDialog(this, "Course approved.");
        } else {
            cs.rejectCourse(courseId);
            JOptionPane.showMessageDialog(this, "Course rejected.");
        }

        loadCourses(); // refresh table
    }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ApproveBtn;
        private javax.swing.JButton DeclineBtn;
        private javax.swing.JButton LogoutBtn;
        private javax.swing.JTable Table;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
    }
