/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.*;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ManageQuiz extends javax.swing.JFrame {

    private Instructor instructor;
    private Course course;
    private Lesson lesson;
    private QuizService quizService;
    private Quiz quiz;


    public ManageQuiz(Instructor instructor, Course course, Lesson lesson) {
        this.instructor = instructor;
        this.course = course;
        this.lesson = lesson;
        initComponents();
        this.setLocationRelativeTo(null);

        quizService = new QuizService();

        if (lesson.getQuiz() == null) {
            quiz = new Quiz("quiz_" + lesson.getLessonId(), lesson.getLessonId(), new ArrayList<>(), 50);
            quizService.addQuizToLesson(course.getCourseId(), lesson.getLessonId(), quiz);
        } else {
            quiz = lesson.getQuiz();
        }

       // loadQuiz();
    }
    /*private void loadQuiz() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        Quiz quiz = lesson.getQuiz();
        if (quiz != null) {
            ArrayList<Question> questions = quiz.getQuestions();
            for (int i = 0; i < questions.size(); i++) {
                Question q = questions.get(i);
                //model.addRow(new Object[]{i + 1, q.getQuestionText(), String.join(", ", q.getOptions()), q.getCorrectAnswer()});
                model.addRow(new Object[]{
                        i + 1,
                        q.getQuestionText(),
                        q.getOptions()[0],
                        q.getOptions()[1],
                        q.getOptions()[2],
                        q.getOptions()[3],
                        q.getCorrectAnswer()
                });
            }
        }
    }*/

    private void addQuestion() {
        JTextField questionField = new JTextField();
        JTextField optionA = new JTextField();
        JTextField optionB = new JTextField();
        JTextField optionC = new JTextField();
        JTextField optionD = new JTextField();
        JTextField correct = new JTextField();

        Object[] message = {
                "Question:", questionField,
                "Option A:", optionA,
                "Option B:", optionB,
                "Option C:", optionC,
                "Option D:", optionD,
                "Correct Answer (A/B/C/D):", correct
        };

        int option = JOptionPane.showConfirmDialog(this, message, "Add Question", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            String qText = questionField.getText();
            String[] opts = new String[]{optionA.getText(), optionB.getText(), optionC.getText(), optionD.getText()};
            String correctAns = correct.getText().toUpperCase();

            // Validate
            if (qText.isEmpty() || opts[0].isEmpty() || opts[1].isEmpty() || opts[2].isEmpty() || opts[3].isEmpty() ||
                    !(correctAns.equals("A") || correctAns.equals("B") || correctAns.equals("C") || correctAns.equals("D"))) {
                JOptionPane.showMessageDialog(this, "Please fill all fields correctly.");
                return;
            }

            String rightAnswer = switch (correctAns) {
                case "A" -> opts[0];
                case "B" -> opts[1];
                case "C" -> opts[2];
                case "D" -> opts[3];
                default -> "";
            };

            Question question = new Question(qText, opts, rightAnswer);
            quizService.addQuestionToQuiz(course.getCourseId(), lesson.getLessonId(), question);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{
                    model.getRowCount() + 1,
                    question.getQuestionText(),
                    question.getOptions()[0],
                    question.getOptions()[1],
                    question.getOptions()[2],
                    question.getOptions()[3],
                    question.getCorrectAnswer()
            });
          //loadQuiz();
        }
    }
    private void saveQuiz() {quizService.addQuizToLesson(course.getCourseId(), lesson.getLessonId(), quiz);
        JOptionPane.showMessageDialog(this, "Quiz saved successfully!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Quiz ");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Question", "A", "B", "C", "D", "Right ans"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Add Question");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestion();
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1)
                        .addGap(60, 60, 60)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManageLessons ml = new ManageLessons(instructor, course);
        ml.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveQuiz();
    }//GEN-LAST:event_jButton1ActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new ManageQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
